### PR TITLE
bug: discuss how to generate the applicationServerKey

### LINKED ISSUE #45: Needs documentation for client-side applicationServerKey paramater
`pushManager.subscribe` takes the option `applicationServerKey` client-side. The Python documentation needs to document how to convert the generated public key into a form that can be used client-side like this.

```javascript
navigator.serviceWorker.register('serviceworker.js').then(
  function(serviceWorkerRegistration) {
    var options = {
      userVisibleOnly: true,
      applicationServerKey: applicationServerKey // <-- how do I convert the public key .pem to this?
    };
    serviceWorkerRegistration.pushManager.subscribe(options).then(
      // ...
  });
```

### PR DESCRIPTION
**Pull request by jrconlin**
closes #45 

@flimm r?

### CODE REVIEW

**Comment by Flimm** [comment]
That's a great new argument! I haven't had time to check yet, but I presume it prints out the `applicationServerKey` parameter in URL-safe Base64 format, which would need to be converted manually using a function like this one on the client-side browser:

```javascript
function urlB64ToUint8Array(base64String) {
  const padding = '='.repeat((4 - base64String.length % 4) % 4);
  const base64 = (base64String + padding)
    .replace(/-/g, '+')
    .replace(/_/g, '/');

  const rawData = window.atob(base64);
  const outputArray = new Uint8Array(rawData.length);

  for (let i = 0; i < rawData.length; ++i) {
    outputArray[i] = rawData.charCodeAt(i);
  }
  return outputArray;
}
```

(This is from Google's sample code.)

Sadly, MDN doesn't mention how to convert Base64 to a Uint8Array like this. So I would like it to be documented here.

**Comment by jrconlin** [comment]
Ah, that's because you don't need to convert the string to use it in Firefox (as [of 54](https://bugzilla.mozilla.org/show_bug.cgi?id=1337348)) .

I'll add a note to point to the Chrome docs for folks that need to.

**Comment by Flimm** [comment]
OK, I'm trying it now:

```
vapid --applicationServerKey
Application Server Key = EIikzDLcDnWoDITvBY1v2ox....


Traceback (most recent call last):
  File "flimm/git/forks/vapid/python/env/bin/vapid", line 11, in <module>
    load_entry_point('py-vapid==1.2.2', 'console_scripts', 'vapid')()
  File "flimm/git/forks/vapid/python/env/lib/python3.6/site-packages/py_vapid-1.2.2-py3.6.egg/py_vapid/main.py", line 104, in main
    token = args.validate
AttributeError: 'Namespace' object has no attribute 'validate'
```

So it prints out the Application Server Key, but then gives a strange error.

The README.md needs to reference this new command-line option.

**Comment by Flimm** [comment]
Great! I don't seem to experience the `Namespace` error any more.

**Pull request merged**
